version: "3.7"

services:
  # PostgreSQL database service
  postgres:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

  # Backend service
  server:
    build:
      context: ./server
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - postgres

  # Frontend service
  client:
    build:
      context: ./client
    container_name: frontend
    ports:
      - "80:80"

  # Nginx service for reverse proxy
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - client
      - server
