version: '3.9'

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: password
      POSTGRES_DB: dev
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: password
      POSTGRES_DB: dev
    ports:
      - '5432:5432'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
