tags:
  - name: guests
    description: guests API
  - name: rooms
    description: rooms API
paths:
  # [GET] guests
  /guests:
    get:
      tags:
        - guests
      summary: Find All guests
      parameters:
        - name: limit
          in: query
          description: Limit
          required: false
          type: integer
        - name: page
          in: query
          description: Page
          required: false
          type: integer
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

    # [POST] guests
    post:
      tags:
        - guests
      summary: Create a guest
      parameters:
        - name: body
          in: body
          description: Guest Object
          required: true
          schema:
            $ref: '#/definitions/guests'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [PUT] guests
  /guests/{id}:
    put:
      tags:
        - guests
      summary: Update a guest
      parameters:
        - name: id
          in: path
          description: 'The ID of the guest'
          required: true
          type: string
        - name: body
          in: body
          description: Guest Object
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              email:
                type: string
              phone_number:
                type: string
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        404:
          description: 'Not Found'
        500:
          description: 'Server Error'

    get:
      tags:
        - guests
      summary: Get a guest by ID
      parameters:
        - name: id
          in: path
          description: 'The ID of the guest'
          required: true
          type: string
      responses:
        200:
          description: 'OK'
        404:
          description: 'Not Found'
        500:
          description: 'Server Error'

  # [GET] rooms
  /rooms:
    get:
      tags:
        - rooms
      summary: Get all rooms
      parameters:
        - name: limit
          in: query
          description: Limit
          required: false
          type: integer
        - name: page
          in: query
          description: Page
          required: false
          type: integer
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
    post:
      tags:
        - rooms
      summary: Create a room
      parameters:
        - name: body
          in: body
          description: Room Object
          required: true
          schema:
            $ref: '#/definitions/rooms'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# definitions
definitions:
  guests:
    type: object
    required:
      - name
      - email
      - phone_number
    properties:
      name:
        type: string
        description: Guest Name
      email:
        type: string
        description: Guest Email
      phone_number:
        type: string
        description: Guest Phone Number
  rooms:
    type: object
    required:
      - room_name
      - room_number
    properties:
      room_name:
        type: string
        description: Room Name
      room_number:
        type: integer
        description: Room Number

schemes:
  - https
  - http
